### ISSUE TITLE
open_manipulator_pro_teleop error!

### ISSUE THREAD

**Issue by YDK18** [ROBOTIS-GIT/open_manipulator_p#27]
I experimented with gazebo and real hardware.
However, a manipulator malfunction occurred.
The control gui, keyboard control, and joystick control all have errors when the x value drops below (ex. 0.25).
My guess seems to be an error in the inverse kinematics of the open manipulator msgs.
I want a solution for this.
Thank you, Please reply.

https://youtu.be/ytdMD7-c3MI

**Comment by JaehyunShim** [comment]
@YDK18 

Thank you for reporting the bug. It should work now. Test it again and let us know the result

Regards,
Ryan

**Comment by Fred159** [comment]
> @YDK18
> 
> Thank you for reporting the bug. It should work now. Test it again and let us know the result
> 
> Regards,
> Ryan

Hello  I am the same team with @YDK18 . I just tested the latest code that uploaded 1 hour ago. However, there is still something wrong. Please refers to below link. 
[https://www.youtube.com/watch?v=p-SLIsoBsak&feature=youtu.be](url)
With the modified code, it seems like manipulator does not hit the ground suddenly at x position at 0.240. 
Actually, I wonder why the manipulator moves like that ? 
But there is no feedback or error message. If arm can't reach the goal position because of the physical limitation, then I think maybe there should be a error report and stop movement. 
Looking forward to your reply.
Thank you.

**Comment by Fred159** [comment]
@rjshim 
Hello  I am the same team with @YDK18 . I just tested the latest code that uploaded 1 hour ago. However, there is still something wrong. Please refers to below link. 
[https://www.youtube.com/watch?v=p-SLIsoBsak&feature=youtu.be](url)
With the modified code, it seems like manipulator does not hit the ground suddenly at x position at 0.240. 
Actually, I wonder why the manipulator moves like that ? 
But there is no feedback or error message. If arm can't reach the goal position because of the physical limitation, then I think maybe there should be a error report and stop movement. 
Looking forward to your reply.
Thank you.

**Comment by JaehyunShim** [comment]
@Fred159

Please download the latest version and test it again. 

![2019-12-02](https://user-images.githubusercontent.com/38637417/70014319-c701af00-15bd-11ea-9df6-08b3e41456a1.png)

**Comment by YDK18** [comment]
> @Fred159
> 
> Please download the latest version and test it again.
> 
> ![2019-12-02](https://user-images.githubusercontent.com/38637417/70014319-c701af00-15bd-11ea-9df6-08b3e41456a1.png)

**Comment by YDK18** [comment]
@rjshim 
Hello. I was trying to test the lastest version. 
The y and z axes ran correctly but axis-x malfunction occured again.
As shown in the picture, a strange posture was output.

![default_gzclient_camera(1)-2019-12-03T11_25_53 801155](https://user-images.githubusercontent.com/38091018/70015595-36c56900-15c1-11ea-9792-bd2baf9de98b.jpg)

**Comment by Fred159** [comment]
@rjshim 
I download the latest version in master at [https://github.com/ROBOTIS-GIT/open_manipulator_pro.git](url). 
We use ubuntu 16.04. LTS. ROS: kinetic
Do you mean the version with kinetic-devel branch? But I also test the kinetic version, it doesn't work either.
Arm works well in y direction and z direction. When arm reached the limitation of the physical size, terminator gave error messages and stop. However the arm still works strange in x direction. Arm moved with a not understandable behavior. 
![Screenshot from 2019-12-03 11-39-33](https://user-images.githubusercontent.com/25920838/70015879-14801b00-15c2-11ea-9465-bff8de859509.png)
![Screenshot from 2019-12-03 11-39-58](https://user-images.githubusercontent.com/25920838/70015880-1518b180-15c2-11ea-8083-52b7ac4dfae4.png)

**Comment by JaehyunShim** [comment]
@YDK18 

Sorry for the late reply. I just fixed fk and ik bugs and updated the package. Please test it and let us know the result. 

Regards,
Ryan

**Comment by JaehyunShim** [comment]
As there have been no updates, I will close this issue.
Ryan
